# Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2-is-node
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: wso2is
  replicas: {{ .Values.wso2.deployment.wso2is.replicas }}
  template:
    metadata:
      name: is-pod
    spec:
      containers:
      - name: wso2-is-container
        image: is-node-1:kubernetes
        ports:
        - containerPort: 9443 
        - containerPort: 4000
        - containerPort: 9763
        - containerPort: 3306

        volumeMounts:
          - name: identity-server-conf
            mountPath: /app/wso2is-6.1.0/repository/conf/deployment.toml
            subPath: deployment.toml
      
      volumes:
        - name: identity-server-conf
          configMap:
            name: identity-server-conf

